In [ ]:
import numpy as np

from sklearn.base import BaseEstimator, ClassifierMixin

from sklearn.utils.validation import validate_data, check_is_fitted

from sklearn.utils.multiclass import unique_labels

from sklearn.metrics import euclidean_distances

from sklearn import datasets


iris_X, iris_y = datasets.load_iris(return_X_y=True)
np.unique(iris_y)

# den Datensatz in zwei teile für test und training aufspalten
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
X = iris_X[indices[:-10]]
Y = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

class TemplateClassifier(ClassifierMixin, BaseEstimator):


    def __init__(self):

        pass


    def fit(self, X, y):


        # Check that X and y have correct shape, set n_features_in_, etc.

        X, y = validate_data(self, X, y)

        # Store the classes seen during fit

        self.classes_ = unique_labels(y)


        self.X_ = X

        self.y_ = y

        # Return the classifier

        return self


    def predict(self, blume):


        # Check if fit has been called

        check_is_fitted(self)


        # Input validation

        iris_X_test = validate_data(self, blume, reset=False)


        closest = np.argmin(euclidean_distances(blume, self.X_), axis=1)

        return self.y_[closest]
    
meineklasse=TemplateClassifier()
blume=TemplateClassifier(iris_X_test[0])

TypeError: TemplateClassifier.__init__() takes 1 positional argument but 2 were given

In [ ]:
import numpy as np

from sklearn.base import BaseEstimator, ClassifierMixin

from sklearn.utils.validation import validate_data, check_is_fitted

from sklearn.utils.multiclass import unique_labels

from sklearn.metrics import euclidean_distances

from sklearn import datasets


iris_X, iris_y = datasets.load_iris(return_X_y=True)
np.unique(iris_y)

# den Datensatz in zwei teile für test und training aufspalten
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
X = iris_X[indices[:-10]]
Y = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

class TemplateClassifier(ClassifierMixin, BaseEstimator):


    def __init__(self):

        pass


    def fit(self, X, y):


        # Check that X and y have correct shape, set n_features_in_, etc.

        X, y = validate_data(self, X, y)

        # Store the classes seen during fit

        self.classes_ = unique_labels(y)


        self.X_ = X

        self.y_ = y

        # Return the classifier

        return self


    def predict(self, blume):


        # Check if fit has been called

        check_is_fitted(self)


        # Input validation

        iris_X_test = validate_data(self, blume, reset=False)


        closest = np.argmin(euclidean_distances(blume, self.X_), axis=1)

        return self.y_[closest]



In [ ]:
meineklasse=TemplateClassifier()

In [ ]:
meineklasse

TemplateClassifier()

In [ ]:
dir meineklasse()



SyntaxError: invalid syntax (<ipython-input-5-eb5249622a43>, line 1)

In [ ]:
dir(meineklasse)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_validate_data',
 '_validate_params',
 'fit',
 'get_metadata_routing',
 'get_params',
 'predict',
 'score',
 'set_params',
 'set_predict_request',
 'set_score_request']

In [ ]:
meineklasse.fit(X,Y)

TemplateClassifier()

In [ ]:
meineklasse.X_

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2

In [ ]:
meineklasse.predict(iris_X_test[0])

ValueError: Expected 2D array, got 1D array instead:
array=[5.6 3.  4.1 1.3].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
meineklasse.predict(iris_X_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [ ]:
print(iris_Y_test)

NameError: name 'iris_Y_test' is not defined

In [ ]:
print(iris_y_test)

[1 1 1 0 0 0 2 1 2 0]
